package com.foxygift.pos.ui.screens.provision

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.foxygift.pos.core.provisioning.QrProvisioningScanner
import com.foxygift.pos.data.repository.ProvisionRepository
import com.foxygift.pos.core.security.PinSecurityManager
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import javax.inject.Inject

data class ProvisionUiState(
    val phase:        ProvisionPhase = ProvisionPhase.IDLE,
    val locationName: String         = "",
    val networkName:  String         = "",
    val terminalId:   String         = "",
    val errorMessage: String?        = null,
)

enum class ProvisionPhase {
    IDLE,
    PERMISSION_DENIED,
    SCANNING,
    PROCESSING,
    SUCCESS,
    ERROR,
}

@HiltViewModel
class ProvisionViewModel @Inject constructor(
    private val qrScanner:          QrProvisioningScanner,
    private val repository:         ProvisionRepository,
    private val pinSecurityManager: PinSecurityManager,
) : ViewModel() {

    private val _uiState = MutableStateFlow(ProvisionUiState())
    val uiState: StateFlow<ProvisionUiState> = _uiState.asStateFlow()

    fun startScanning() {
        _uiState.value = ProvisionUiState(phase = ProvisionPhase.SCANNING)
    }

    fun reset() {
        _uiState.value = ProvisionUiState(phase = ProvisionPhase.IDLE)
    }

    fun onPermissionDenied() {
        _uiState.value = _uiState.value.copy(phase = ProvisionPhase.PERMISSION_DENIED)
    }

    /**
     * Called by [CameraQrScanner] when ML Kit detects a QR code.
     * Transitions immediately to PROCESSING, then validates asynchronously.
     */
    fun onQrScanned(rawQr: String) {
        _uiState.value = _uiState.value.copy(phase = ProvisionPhase.PROCESSING)

        viewModelScope.launch {
            // Retrieve the stored master key (set during factory provisioning
            // or entered manually in advanced settings). Falls back to a
            // blank key so the scanner returns Invalid — never crashes.
            val masterKeyHex = repository.getMasterKeyHex()

            val result = qrScanner.parse(rawQr, masterKeyHex)

            when (result) {
                is QrProvisioningScanner.ScanResult.Success -> {
                    val config = result.config

                    // Persist provisioning config to EncryptedSharedPreferences
                    repository.saveProvisioningConfig(config)

                    // Unlock any lockout state from previous failed PIN attempts
                    pinSecurityManager.unlockWithProvisioningQr(true)

                    _uiState.value = ProvisionUiState(
                        phase        = ProvisionPhase.SUCCESS,
                        locationName = config.locationName,
                        networkName  = config.networkName,
                        terminalId   = config.terminalId,
                    )
                }

                is QrProvisioningScanner.ScanResult.Invalid -> {
                    _uiState.value = _uiState.value.copy(
                        phase        = ProvisionPhase.ERROR,
                        errorMessage = result.reason,
                    )
                }

                QrProvisioningScanner.ScanResult.NotAProvisioningQr -> {
                    _uiState.value = _uiState.value.copy(
                        phase        = ProvisionPhase.ERROR,
                        errorMessage = "Not a FoxyGift provisioning QR.\nPlease scan the correct QR generated by the Vendor Tool.",
                    )
                }
            }
        }
    }
}
