package com.foxygift.pos.ui.theme

import androidx.compose.runtime.compositionLocalOf

/** All localised UI strings for FoxyGift POS. */
data class AppStrings(
    // ── App ──────────────────────────────────────────────
    val appName: String,
    val selectOperation: String,

    // ── Home operations ──────────────────────────────────
    val opIssue: String,
    val opRedeem: String,
    val opBalance: String,
    val opProlong: String,
    val opVoid: String,
    val opZReport: String,
    val opDailyOperations: String,

    // ── User Session & Roles ─────────────────────────────
    val logout: String,
    val switchUser: String,
    val roleAdmin: String,
    val roleCashier: String,
    val roleProlong: String,
    val loggedInAs: String,

    // ── Access Control & PIN Dialog ──────────────────────
    val accessDenied: String,
    val adminPinRequired: String,
    val prolongPinRequired: String,
    val enterPinToAuthorize: String,
    val authorizeSuccess: String,
    val invalidPin: String,

    // ── Daily Operations Journal ─────────────────────────
    val dailyOperationsTitle: String,
    val dailyTotalOperations: String,
    val dailyTurnover: String,
    val receiptNo: String,
    val time: String,
    val cardNumber: String,
    val amount: String,
    val balanceAfter: String,
    val status: String,
    val noOperationsToday: String,
    val filterAll: String,
    val filterIssue: String,
    val filterRedeem: String,
    val filterProlong: String,
    val filterVoid: String,
    val exportCsv: String,
    val exportSuccess: String,
    val exportError: String,

    // ── PIN Screen ───────────────────────────────────────
    val pinUnlockPrompt: String,
    val wrongPinRemaining: String,
    val wrongPinNextLocks: String,
    val keyboardLocked: String,
    val permanentlyLocked: String,
    val scanQrToUnlock: String,
    val provisionTerminal: String,
    val scanQr: String,

    // ── NFC overlay ──────────────────────────────────────
    val nfcTapCard: String,
    val nfcReading: String,
    val nfcWriting: String,
    val nfcDoNotRemove: String,
    val nfcKeepOnReader: String,
    val nfcSuccess: String,
    val nfcFailed: String,
    val nfcCardBalance: String,
    val nfcClose: String,

    // ── Issue / Top-Up screen ─────────────────────────────
    val issueTitle: String,
    val issueNominalValue: String,
    val issueValidity: String,
    val issueTapButton: String,

    // ── Redeem screen ─────────────────────────────────────
    val redeemTitle: String,
    val redeemAmountLabel: String,
    val redeemTapButton: String,

    // ── Balance enquiry ───────────────────────────────────
    val balanceTitle: String,
    val balanceExpiry: String,
    val balanceExpired: String,

    // ── Prolong screen ────────────────────────────────────
    val prolongTitle: String,
    val prolongMonths: String,
    val prolongCurrentExpiry: String,
    val prolongTapButton: String,
    val prolongCardTitle: String,
    val extendCardBy: String,
    val extensionPeriod: String,
    val prolongCardInstruction: String,

    // ── Z-Report ──────────────────────────────────────────
    val zReportShiftTitle: String,
    val closeShift: String,
    val sendToTelegram: String,
    val totalTransactions: String,
    val kpiIssued: String,
    val kpiRedeemed: String,
    val kpiLiability: String,
    val kpiVoids: String,
    val operationsCount: String,

    // ── Settings ──────────────────────────────────────────
    val settingsTitle: String,
    val settingsTerminalInfo: String,
    val settingsTerminalId: String,
    val settingsLocation: String,
    val settingsMerchantId: String,
    val settingsCurrency: String,
    val settingsNetwork: String,
    val settingsAlerts: String,
    val settingsTelegram: String,
    val settingsBotToken: String,
    val settingsChatId: String,
    val settingsDisplay: String,
    val settingsDarkMode: String,
    val settingsKiosk: String,
    val settingsKioskLock: String,
    val settingsKioskInfo: String,
    val settingsDatabase: String,
    val settingsExportCsv: String,
    val settingsProvision: String,
    val settingsScanQr: String,
    val settingsLanguage: String,

    // ── Void / Cancellation screen ────────────────────────
    val cancelTitle: String,
    val cancelSelectTxPrompt: String,
    val cancelTapCardPrompt: String,
    val cancelSuccess: String,
    val cancelNotTodayError: String,
    val cancelCardMismatchError: String,
    val cancelInsufficientBalanceError: String,
    val cancelAlreadyVoidedError: String,
    val cancelImpossibleComment: String,
    val primaryOperationBadge: String,

    // ── Errors ────────────────────────────────────────────
    val errNfcRead: String,
    val errInsufficientBalance: String,
    val errExpired: String,
    val errCloneDetected: String,
    val errWrongMerchant: String,
    val errAuthFailed: String,

    // ── Common ────────────────────────────────────────────
    val back: String,
    val confirm: String,
    val cancel: String,
    val currency: String,
    val months: String,

    // ── Hero subtitles, confirmation & warnings ───────────
    val opIssueSubtitle: String,
    val opRedeemSubtitle: String,
    val errExhausted: String,
    val overwriteBalanceTitle: String,
    val overwriteBalanceMessage: String,
    val overwriteBalanceConfirm: String,
    val exitConfirmTitle: String,
    val exitConfirmMessage: String,
    val exitConfirmButton: String,
    val shiftClosedSuccess: String,
    val shiftAlreadyClosed: String,
    val tgSentSuccess: String,
    val tgSendFailed: String,
    val tgNotConfigured: String,
    val settingsTgTokenPrompt: String,
    val settingsTgChatPrompt: String,
    val settingsTgChannelHint: String,
    val settingsSave: String,
)

// ─────────────────────────────────────────────────────────────────────────────
// Translations
// ─────────────────────────────────────────────────────────────────────────────

val StringsEn = AppStrings(
    appName                = "🦊 FoxyGift POS",
    selectOperation        = "Select operation",
    opIssue                = "ISSUE / TOP UP",
    opRedeem               = "REDEEM CARD",
    opBalance              = "BALANCE CHECK",
    opProlong              = "PROLONG CARD",
    opVoid                 = "VOID / REFUND",
    opZReport              = "Z-REPORT",
    opDailyOperations      = "DAILY LOG",
    logout                 = "Logout",
    switchUser             = "Switch User",
    roleAdmin              = "Administrator",
    roleCashier            = "Cashier",
    roleProlong            = "Supervisor",
    loggedInAs             = "Role",
    accessDenied           = "Access Denied",
    adminPinRequired       = "Administrator PIN required",
    prolongPinRequired     = "Prolongation or Admin PIN required",
    enterPinToAuthorize    = "Enter PIN to authorize operation",
    authorizeSuccess       = "Authorization successful",
    invalidPin             = "Invalid PIN",
    dailyOperationsTitle   = "Daily Operations Journal",
    dailyTotalOperations   = "Total Operations",
    dailyTurnover          = "Turnover",
    receiptNo              = "Receipt #",
    time                   = "Time",
    cardNumber             = "Card Number",
    amount                 = "Amount",
    balanceAfter           = "Balance",
    status                 = "Status",
    noOperationsToday      = "No operations recorded for this shift",
    filterAll              = "All",
    filterIssue            = "Issue",
    filterRedeem           = "Redeem",
    filterProlong          = "Prolong",
    filterVoid             = "Void",
    exportCsv              = "Export CSV",
    exportSuccess          = "CSV file sent to email client",
    exportError            = "Failed to export CSV file",
    pinUnlockPrompt        = "Enter your PIN to unlock",
    wrongPinRemaining      = "Wrong PIN. %d attempts remaining.",
    wrongPinNextLocks      = "Wrong PIN. Next failure will lock the terminal.",
    keyboardLocked         = "Keyboard locked: %ds",
    permanentlyLocked      = "🔴 PERMANENTLY LOCKED",
    scanQrToUnlock         = "Scan provisioning QR to unlock",
    provisionTerminal      = "Provision terminal",
    scanQr                 = "Scan QR",
    nfcTapCard             = "Tap gift card to reader",
    nfcReading             = "Reading card…",
    nfcWriting             = "Writing to card… DO NOT REMOVE",
    nfcDoNotRemove         = "DO NOT REMOVE THE CARD",
    nfcKeepOnReader        = "Keep card on reader until confirmed",
    nfcSuccess             = "✓ ",
    nfcFailed              = "✗ Operation failed",
    nfcCardBalance         = "Card balance",
    nfcClose               = "Close",
    issueTitle             = "Issue / Top Up Card",
    issueNominalValue      = "Amount",
    issueValidity          = "Validity Period",
    issueTapButton         = "TAP CARD TO ISSUE  •  %s",
    redeemTitle            = "Redeem Gift Card",
    redeemAmountLabel      = "Amount to Redeem",
    redeemTapButton        = "TAP CARD  •  REDEEM %s",
    balanceTitle           = "Balance Enquiry",
    balanceExpiry          = "Expires",
    balanceExpired         = "⚠ EXPIRED",
    prolongTitle           = "Prolong Card",
    prolongMonths          = "Add months",
    prolongCurrentExpiry   = "Current expiry",
    prolongTapButton       = "TAP CARD  •  EXTEND +%d MONTHS",
    prolongCardTitle       = "Prolong Card Validity",
    extendCardBy           = "Extend card by",
    extensionPeriod        = "Extension period",
    prolongCardInstruction = "Tap card to reader to extend validity by %d months.",
    zReportShiftTitle      = "Z-Report — Shift %s",
    closeShift             = "CLOSE SHIFT",
    sendToTelegram         = "Send to Telegram",
    totalTransactions      = "Total Transactions",
    kpiIssued              = "ISSUED",
    kpiRedeemed            = "REDEEMED",
    kpiLiability           = "LIABILITY",
    kpiVoids               = "VOIDS",
    operationsCount        = "operations",
    settingsTitle          = "Settings",
    settingsTerminalInfo   = "Terminal Information",
    settingsTerminalId     = "Terminal ID",
    settingsLocation       = "Location",
    settingsMerchantId     = "Merchant ID",
    settingsCurrency       = "Currency",
    settingsNetwork        = "Network",
    settingsAlerts         = "Alerts & Notifications",
    settingsTelegram       = "Telegram Alerts",
    settingsBotToken       = "Bot Token",
    settingsChatId         = "Chat ID",
    settingsDisplay        = "Display",
    settingsDarkMode       = "Dark Mode",
    settingsKiosk          = "Kiosk Mode",
    settingsKioskLock      = "Lock Task Mode",
    settingsKioskInfo      = "Kiosk mode requires Device Owner policy. Contact your IT administrator.",
    settingsDatabase       = "Database",
    settingsExportCsv      = "Export Database (CSV)",
    settingsProvision      = "Re-Provisioning",
    settingsScanQr         = "Scan New Provisioning QR",
    settingsLanguage       = "Language",
    errNfcRead             = "NFC error: ",
    errInsufficientBalance = "Insufficient balance",
    errExpired             = "Card expired",
    errCloneDetected       = "⚠ Card signature invalid — possible counterfeit card.",
    errWrongMerchant       = "This card belongs to a different merchant network.",
    errAuthFailed          = "Authentication failed",
    back                   = "Back",
    confirm                = "Confirm",
    cancel                 = "Cancel",
    currency               = "EUR",
    months                 = "m",
    cancelTitle                    = "Transaction Cancellation",
    cancelSelectTxPrompt           = "Select a transaction to cancel",
    cancelTapCardPrompt            = "Tap card to cancel receipt #%s",
    cancelSuccess                  = "✓ Receipt #%s cancelled successfully",
    cancelNotTodayError            = "Transaction was not conducted today.",
    cancelCardMismatchError        = "Scanned card does not match the transaction card.",
    cancelInsufficientBalanceError = "Insufficient card balance.",
    cancelAlreadyVoidedError       = "Transaction is already cancelled.",
    cancelImpossibleComment        = "Cancellation impossible.",
    primaryOperationBadge          = "★ PRIMARY",
    opIssueSubtitle                = "Issue new card or top up balance",
    opRedeemSubtitle               = "Pay purchase or redeem card balance",
    errExhausted                   = "Card balance is fully exhausted.",
    overwriteBalanceTitle          = "Warning: Active Balance",
    overwriteBalanceMessage        = "This card already has an active balance: %s. Re-issuing will permanently destroy the existing balance. Continue?",
    overwriteBalanceConfirm        = "Overwrite Balance",
    exitConfirmTitle               = "Exit Application",
    exitConfirmMessage             = "Are you sure you want to log out or exit the POS terminal?",
    exitConfirmButton              = "Confirm Exit",
    shiftClosedSuccess             = "Shift closed successfully. Z-Report generated.",
    shiftAlreadyClosed             = "Shift for today has already been closed.",
    tgSentSuccess                  = "Z-Report successfully sent to Telegram.",
    tgSendFailed                   = "Failed to send to Telegram: %s",
    tgNotConfigured                = "Telegram is not configured in terminal settings.",
    settingsTgTokenPrompt          = "Bot Token (e.g. 123456:ABC...)",
    settingsTgChatPrompt           = "Chat ID / Channel (e.g. -100... or @channel)",
    settingsTgChannelHint          = "Channel: @channel or -100... (Bot MUST be an admin in the channel with Post Messages permission)",
    settingsSave                   = "Save Settings",
)

val StringsRu = AppStrings(
    appName                = "🦊 FoxyGift POS",
    selectOperation        = "Выберите операцию",
    opIssue                = "ВЫДАЧА / ПОПОЛНЕНИЕ",
    opRedeem               = "СПИСАНИЕ",
    opBalance              = "БАЛАНС",
    opProlong              = "ПРОДЛЕНИЕ",
    opVoid                 = "АННУЛИРОВАНИЕ",
    opZReport              = "Z-ОТЧЁТ",
    opDailyOperations      = "ЖУРНАЛ ОПЕРАЦИЙ",
    logout                 = "Выход",
    switchUser             = "Смена пользователя",
    roleAdmin              = "Администратор",
    roleCashier            = "Кассир",
    roleProlong            = "Продление",
    loggedInAs             = "Роль",
    accessDenied           = "Доступ запрещен",
    adminPinRequired       = "Требуются права Администратора",
    prolongPinRequired     = "Требуется PIN продления или Администратора",
    enterPinToAuthorize    = "Введите PIN для авторизации действия",
    authorizeSuccess       = "Авторизация успешна",
    invalidPin             = "Неверный PIN",
    dailyOperationsTitle   = "Дневные операции",
    dailyTotalOperations   = "Всего операций",
    dailyTurnover          = "Оборот смены",
    receiptNo              = "Чек #",
    time                   = "Время",
    cardNumber             = "Номер карты",
    amount                 = "Сумма",
    balanceAfter           = "Остаток",
    status                 = "Статус",
    noOperationsToday      = "За текущую смену операций не найдено",
    filterAll              = "Все",
    filterIssue            = "Выдача",
    filterRedeem           = "Списание",
    filterProlong          = "Продление",
    filterVoid             = "Аннулирование",
    exportCsv              = "Экспорт CSV",
    exportSuccess          = "CSV отчёт передан в почтовый клиент",
    exportError            = "Ошибка экспорта CSV отчёта",
    pinUnlockPrompt        = "Введите PIN для входа",
    wrongPinRemaining      = "Неверный PIN. Осталось попыток: %d",
    wrongPinNextLocks      = "Неверный PIN. Следующая ошибка заблокирует терминал.",
    keyboardLocked         = "Клавиатура заблокирована: %d с",
    permanentlyLocked      = "🔴 ТЕРМИНАЛ ЗАБЛОКИРОВАН",
    scanQrToUnlock         = "Сканируйте QR привязки для разблокировки",
    provisionTerminal      = "Привязка терминала",
    scanQr                 = "Сканировать QR",
    nfcTapCard             = "Приложите карту к считывателю",
    nfcReading             = "Чтение карты…",
    nfcWriting             = "Запись на карту… НЕ УБИРАЙТЕ",
    nfcDoNotRemove         = "НЕ УБИРАЙТЕ КАРТУ",
    nfcKeepOnReader        = "Держите карту на считывателе до подтверждения",
    nfcSuccess             = "✓ ",
    nfcFailed              = "✗ Ошибка операции",
    nfcCardBalance         = "Баланс карты",
    nfcClose               = "Закрыть",
    issueTitle             = "Выдача / Пополнение карты",
    issueNominalValue      = "Сумма",
    issueValidity          = "Срок действия",
    issueTapButton         = "ПРИЛОЖИТЬ КАРТУ  •  %s",
    redeemTitle            = "Списание с карты",
    redeemAmountLabel      = "Сумма к списанию",
    redeemTapButton        = "ПРИЛОЖИТЬ КАРТУ  •  СПИСАТЬ %s",
    balanceTitle           = "Проверка баланса",
    balanceExpiry          = "Действует до",
    balanceExpired         = "⚠ ПРОСРОЧЕНА",
    prolongTitle           = "Продление карты",
    prolongMonths          = "Добавить месяцев",
    prolongCurrentExpiry   = "Текущий срок",
    prolongTapButton       = "ПРИЛОЖИТЬ КАРТУ  •  +%d МЕС.",
    prolongCardTitle       = "Продление срока карты",
    extendCardBy           = "Продлить карту на",
    extensionPeriod        = "Период продления",
    prolongCardInstruction = "Приложите карту для продления срока на %d мес.",
    zReportShiftTitle      = "Z-Отчёт — Смена %s",
    closeShift             = "ЗАКРЫТЬ СМЕНУ",
    sendToTelegram         = "Отправить в Telegram",
    totalTransactions      = "Всего транзакций",
    kpiIssued              = "ВЫДАНО",
    kpiRedeemed            = "ПОГАШЕНО",
    kpiLiability           = "ОБЯЗАТЕЛЬСТВА",
    kpiVoids               = "АННУЛИРОВАНО",
    operationsCount        = "операций",
    settingsTitle          = "Настройки",
    settingsTerminalInfo   = "Информация о терминале",
    settingsTerminalId     = "ID терминала",
    settingsLocation       = "Локация",
    settingsMerchantId     = "ID мерчанта",
    settingsCurrency       = "Валюта",
    settingsNetwork        = "Сеть",
    settingsAlerts         = "Уведомления",
    settingsTelegram       = "Telegram-уведомления",
    settingsBotToken       = "Токен бота",
    settingsChatId         = "Chat ID",
    settingsDisplay        = "Отображение",
    settingsDarkMode       = "Тёмная тема",
    settingsKiosk          = "Режим киоска",
    settingsKioskLock      = "Блокировка задач",
    settingsKioskInfo      = "Режим киоска требует политики Device Owner. Обратитесь к администратору.",
    settingsDatabase       = "База данных",
    settingsExportCsv      = "Экспорт базы данных (CSV)",
    settingsProvision      = "Перепривязка терминала",
    settingsScanQr         = "Сканировать QR привязки",
    settingsLanguage       = "Язык",
    errNfcRead             = "Ошибка NFC: ",
    errInsufficientBalance = "Недостаточно средств",
    errExpired             = "Карта просрочена",
    errCloneDetected       = "⚠ Подпись карты недействительна — возможна подделка.",
    errWrongMerchant       = "Эта карта принадлежит другой сети мерчанта.",
    errAuthFailed          = "Ошибка аутентификации",
    back                   = "Назад",
    confirm                = "Подтвердить",
    cancel                 = "Отмена",
    currency               = "EUR",
    months                 = "мес.",
    cancelTitle                    = "Аннулирование сделки",
    cancelSelectTxPrompt           = "Выберите сделку для аннулирования",
    cancelTapCardPrompt            = "Приложите карту для аннулирования чека #%s",
    cancelSuccess                  = "✓ Чек #%s успешно аннулирован",
    cancelNotTodayError            = "Сделка проведена не сегодня.",
    cancelCardMismatchError        = "Считанная карта не совпадает со сделкой.",
    cancelInsufficientBalanceError = "На карте не хватает средств.",
    cancelAlreadyVoidedError       = "Сделка уже аннулирована.",
    cancelImpossibleComment        = "Аннулирование невозможно.",
    primaryOperationBadge          = "★ ОСНОВНАЯ",
    opIssueSubtitle                = "Выдача новой карты или пополнение",
    opRedeemSubtitle               = "Оплата покупки или списание баланса",
    errExhausted                   = "Баланс карты полностью исчерпан.",
    overwriteBalanceTitle          = "Внимание! На карте есть средства",
    overwriteBalanceMessage        = "На этой карте уже есть активный баланс: %s. Повторная выдача уничтожит текущие средства! Продолжить?",
    overwriteBalanceConfirm        = "Перезаписать баланс",
    exitConfirmTitle               = "Выход из программы",
    exitConfirmMessage             = "Вы уверены, что хотите выйти из учетной записи / сменить пользователя?",
    exitConfirmButton              = "Подтвердить выход",
    shiftClosedSuccess             = "Смена успешно закрыта. Z-отчет сформирован.",
    shiftAlreadyClosed             = "Смена на сегодня уже закрыта.",
    tgSentSuccess                  = "Z-отчет успешно отправлен в Telegram.",
    tgSendFailed                   = "Ошибка отправки в Telegram: %s",
    tgNotConfigured                = "Telegram не настроен в конфигурации терминала.",
    settingsTgTokenPrompt          = "Bot Token (например, 123456:ABC...)",
    settingsTgChatPrompt           = "Chat ID / Канал (например, -100... или @канал)",
    settingsTgChannelHint          = "Канал: @channel или -100... (Бот ОБЯЗАТЕЛЬНО должен быть админом с правом публикации)",
    settingsSave                   = "Сохранить",
)

val StringsLv = AppStrings(
    appName                = "🦊 FoxyGift POS",
    selectOperation        = "Izvēlieties darbību",
    opIssue                = "IZSNIEGŠANA / PAPILD.",
    opRedeem               = "IZMANTOT KARTI",
    opBalance              = "ATLIKUMS",
    opProlong              = "PAGARINĀT",
    opVoid                 = "ANULĒT",
    opZReport              = "Z-PĀRSKATS",
    opDailyOperations      = "DIENAS ŽURNĀLS",
    logout                 = "Iziet",
    switchUser             = "Mainīt lietotāju",
    roleAdmin              = "Administrators",
    roleCashier            = "Kasieris",
    roleProlong            = "Pārraugs",
    loggedInAs             = "Loma",
    accessDenied           = "Piekļuve liegta",
    adminPinRequired       = "Nepieciešams administratora PIN",
    prolongPinRequired     = "Nepieciešams pagarināšanas vai admin PIN",
    enterPinToAuthorize    = "Ievadiet PIN darbības apstiprināšanai",
    authorizeSuccess       = "Autorizācija veiksmīga",
    invalidPin             = "Nederīgs PIN",
    dailyOperationsTitle   = "Dienas operāciju žurnāls",
    dailyTotalOperations   = "Kopā operācijas",
    dailyTurnover          = "Apgrozījums",
    receiptNo              = "Čeks #",
    time                   = "Laiks",
    cardNumber             = "Kartes numurs",
    amount                 = "Summa",
    balanceAfter           = "Atlikums",
    status                 = "Statuss",
    noOperationsToday      = "Šajā maiņā nav reģistrētu operāciju",
    filterAll              = "Visi",
    filterIssue            = "Izsniegts",
    filterRedeem           = "Izmantots",
    filterProlong          = "Pagarināts",
    filterVoid             = "Anulēts",
    exportCsv              = "Eksportēt CSV",
    exportSuccess          = "CSV fails nosūtīts e-pasta klientam",
    exportError            = "Neizdevās eksportēt CSV failu",
    pinUnlockPrompt        = "Ievadiet PIN, lai atbloķētu",
    wrongPinRemaining      = "Nepareizs PIN. Atlicis mēģinājumu: %d",
    wrongPinNextLocks      = "Nepareizs PIN. Nākamā kļūda bloķēs termināli.",
    keyboardLocked         = "Tastatūra bloķēta: %d s",
    permanentlyLocked      = "🔴 NEATGRIEZENISKI BLOĶĒTS",
    scanQrToUnlock         = "Skenējiet reģistrācijas QR atbloķēšanai",
    provisionTerminal      = "Termināļa iestatīšana",
    scanQr                 = "Skenēt QR",
    nfcTapCard             = "Pielieciet karti pie lasītāja",
    nfcReading             = "Lasa karti…",
    nfcWriting             = "Ieraksta karti… NEATRAUJIET",
    nfcDoNotRemove         = "NEATRAUJIET KARTI",
    nfcKeepOnReader        = "Turiet karti uz lasītāja līdz apstiprināšanai",
    nfcSuccess             = "✓ ",
    nfcFailed              = "✗ Darbība neizdevās",
    nfcCardBalance         = "Kartes atlikums",
    nfcClose               = "Aizvērt",
    issueTitle             = "Izsniegt / Papildināt karti",
    issueNominalValue      = "Summa",
    issueValidity          = "Derīguma termiņš",
    issueTapButton         = "PIELIKT KARTI  •  %s",
    redeemTitle            = "Izmantot dāvanu karti",
    redeemAmountLabel      = "Summa",
    redeemTapButton        = "PIELIKT KARTI  •  %s",
    balanceTitle           = "Atlikuma pārbaude",
    balanceExpiry          = "Derīgs līdz",
    balanceExpired         = "⚠ BEIDZIES",
    prolongTitle           = "Pagarināt karti",
    prolongMonths          = "Pievienot mēnešus",
    prolongCurrentExpiry   = "Pašreizējais termiņš",
    prolongTapButton       = "PIELIKT KARTI  •  +%d MĒN.",
    prolongCardTitle       = "Pagarināt kartes derīgumu",
    extendCardBy           = "Pagarināt karti par",
    extensionPeriod        = "Pagarināšanas periods",
    prolongCardInstruction = "Pielieciet karti, lai pagarinātu termiņu par %d mēn.",
    zReportShiftTitle      = "Z-Pārskats — Maiņa %s",
    closeShift             = "SLĒGT MAIŅU",
    sendToTelegram         = "Sūtīt uz Telegram",
    totalTransactions      = "Kopā transakcijas",
    kpiIssued              = "IZSNIEGTS",
    kpiRedeemed            = "IZMANTOTS",
    kpiLiability           = "SAISTĪBAS",
    kpiVoids               = "ANULĒTS",
    operationsCount        = "operācijas",
    settingsTitle          = "Iestatījumi",
    settingsTerminalInfo   = "Termināļa informācija",
    settingsTerminalId     = "Termināļa ID",
    settingsLocation       = "Atrašanās vieta",
    settingsMerchantId     = "Tirgotāja ID",
    settingsCurrency       = "Valūta",
    settingsNetwork        = "Tīkls",
    settingsAlerts         = "Paziņojumi",
    settingsTelegram       = "Telegram paziņojumi",
    settingsBotToken       = "Bota marķieris",
    settingsChatId         = "Chat ID",
    settingsDisplay        = "Displejs",
    settingsDarkMode       = "Tumšais režīms",
    settingsKiosk          = "Kioskа režīms",
    settingsKioskLock      = "Uzdevumu bloķēšana",
    settingsKioskInfo      = "Kioskа režīmam nepieciešama Device Owner politika. Sazinieties ar administratoru.",
    settingsDatabase       = "Datubāze",
    settingsExportCsv      = "Eksportēt datubāzi (CSV)",
    settingsProvision      = "Atkārtota reģistrācija",
    settingsScanQr         = "Skenēt QR kodu",
    settingsLanguage       = "Valoda",
    errNfcRead             = "NFC kļūda: ",
    errInsufficientBalance = "Nepietiekams atlikums",
    errExpired             = "Kartes termiņš beidzies",
    errCloneDetected       = "⚠ Kartes paraksts nav derīgs — iespējams viltojums.",
    errWrongMerchant       = "Šī karte pieder citam tirgotāju tīklam.",
    errAuthFailed          = "Autentifikācija neizdevās",
    back                   = "Atpakaļ",
    confirm                = "Apstiprināt",
    cancel                 = "Atcelt",
    currency               = "EUR",
    months                 = "mēn.",
    cancelTitle                    = "Darījuma anulēšana",
    cancelSelectTxPrompt           = "Izvēlieties anulējamo darījumu",
    cancelTapCardPrompt            = "Pielieciet karti čeka #%s anulēšanai",
    cancelSuccess                  = "✓ Čeks #%s veiksmīgi anulēts",
    cancelNotTodayError            = "Darījums nav veikts šodien.",
    cancelCardMismatchError        = "Nolasītā karte neatbilst darījumam.",
    cancelInsufficientBalanceError = "Kartē nepietiek līdzekļu.",
    cancelAlreadyVoidedError       = "Darījums jau ir anulēts.",
    cancelImpossibleComment        = "Anulēšana nav iespējama.",
    primaryOperationBadge          = "★ PAMATA",
    opIssueSubtitle                = "Jaunas kartes izsniegšana vai papildināšana",
    opRedeemSubtitle               = "Apmaksa vai kartes atlikuma norakstīšana",
    errExhausted                   = "Kartes atlikums ir pilnībā iztērēts.",
    overwriteBalanceTitle          = "Uzmanību! Kartē ir nauda",
    overwriteBalanceMessage        = "Šai kartei jau ir aktīvs atlikums: %s. Atkārtota izsniegšana dzēsīs esošos līdzekļus! Vai turpināt?",
    overwriteBalanceConfirm        = "Pārrakstīt atlikumu",
    exitConfirmTitle               = "Iziet no programmas",
    exitConfirmMessage             = "Vai tiešām vēlaties iziet vai mainīt lietotāju?",
    exitConfirmButton              = "Apstiprināt iziešanu",
    shiftClosedSuccess             = "Maiņa veiksmīgi slēgta. Z-pārskats izveidots.",
    shiftAlreadyClosed             = "Šodienas maiņa jau ir slēgta.",
    tgSentSuccess                  = "Z-pārskats veiksmīgi nosūtīts uz Telegram.",
    tgSendFailed                   = "Kļūda nosūtot uz Telegram: %s",
    tgNotConfigured                = "Telegram nav konfigurēts termināļa iestatījumos.",
    settingsTgTokenPrompt          = "Bot Token (piem., 123456:ABC...)",
    settingsTgChatPrompt           = "Chat ID / Kanāls (piem., -100... vai @kanals)",
    settingsTgChannelHint          = "Kanāls: @kanals vai -100... (Botam OBLIGĀTI jābūt kanāla administratoram ar tiesībām sūtīt ziņas)",
    settingsSave                   = "Saglabāt",
)

val StringsEt = AppStrings(
    appName                = "🦊 FoxyGift POS",
    selectOperation        = "Vali toiming",
    opIssue                = "VÄLJASTA / LAADI",
    opRedeem               = "LUNASTA KAART",
    opBalance              = "SALDO",
    opProlong              = "PIKENDA",
    opVoid                 = "TÜHISTA",
    opZReport              = "Z-ARUANNE",
    opDailyOperations      = "PÄEVASED TEHINGUD",
    logout                 = "Logi välja",
    switchUser             = "Vaheta kasutajat",
    roleAdmin              = "Administraator",
    roleCashier            = "Kassapidaja",
    roleProlong            = "Ülevaataja",
    loggedInAs             = "Roll",
    accessDenied           = "Juurdepääs keelatud",
    adminPinRequired       = "Nõutav administraatori PIN",
    prolongPinRequired     = "Vajalik pikendamise või admini PIN",
    enterPinToAuthorize    = "Toimingu kinnitamiseks sisestage PIN",
    authorizeSuccess       = "Autoriseerimine õnnestus",
    invalidPin             = "Vale PIN",
    dailyOperationsTitle   = "Päevaste tehingute päevik",
    dailyTotalOperations   = "Tehinguid kokku",
    dailyTurnover          = "Käive",
    receiptNo              = "Kviitung #",
    time                   = "Aeg",
    cardNumber             = "Kaardi number",
    amount                 = "Summa",
    balanceAfter           = "Jääk",
    status                 = "Olek",
    noOperationsToday      = "Selles vahetuses tehinguid pole",
    filterAll              = "Kõik",
    filterIssue            = "Väljastatud",
    filterRedeem           = "Lunastatud",
    filterProlong          = "Pikendatud",
    filterVoid             = "Tühistatud",
    exportCsv              = "Ekspordi CSV",
    exportSuccess          = "CSV fail edastatud meilikliendile",
    exportError            = "CSV eksport ebaõnnestus",
    pinUnlockPrompt        = "Sisestage avamiseks PIN",
    wrongPinRemaining      = "Vale PIN. Katseid jäänud: %d",
    wrongPinNextLocks      = "Vale PIN. Järgmine viga lukustab seadme.",
    keyboardLocked         = "Klaviatuur lukustatud: %d s",
    permanentlyLocked      = "🔴 PÜSIVALT LUKUSTATUD",
    scanQrToUnlock         = "Skannige avamiseks QR-kood",
    provisionTerminal      = "Terminali seadistamine",
    scanQr                 = "Skanni QR",
    nfcTapCard             = "Aseta kaart lugerile",
    nfcReading             = "Loen kaarti…",
    nfcWriting             = "Kirjutan kaardile… ÄRA EEMALda",
    nfcDoNotRemove         = "ÄRA EEMALDA KAARTI",
    nfcKeepOnReader        = "Hoia kaarti lugejal kuni kinnituseni",
    nfcSuccess             = "✓ ",
    nfcFailed              = "✗ Toiming ebaõnnestus",
    nfcCardBalance         = "Kaardi saldo",
    nfcClose               = "Sulge",
    issueTitle             = "Väljasta / Laadi kaart",
    issueNominalValue      = "Summa",
    issueValidity          = "Kehtivusaeg",
    issueTapButton         = "ASETA KAART  •  %s",
    redeemTitle            = "Lunasta kinkekaart",
    redeemAmountLabel      = "Lunastatav summa",
    redeemTapButton        = "ASETA KAART  •  LUNASTA %s",
    balanceTitle           = "Saldo päring",
    balanceExpiry          = "Kehtib kuni",
    balanceExpired         = "⚠ AEGUNUD",
    prolongTitle           = "Pikenda kaarti",
    prolongMonths          = "Lisa kuud",
    prolongCurrentExpiry   = "Praegune tähtaeg",
    prolongTapButton       = "ASETA KAART  •  +%d KUUD",
    prolongCardTitle       = "Kaardi kehtivuse pikendamine",
    extendCardBy           = "Pikenda kaarti",
    extensionPeriod        = "Pikendusperiood",
    prolongCardInstruction = "Asetage kaart lugerile, et pikendada kehtivust %d kuu võrra.",
    zReportShiftTitle      = "Z-Aruanne — Vahetus %s",
    closeShift             = "SULGE VAHETUS",
    sendToTelegram         = "Saada Telegrammi",
    totalTransactions      = "Tehinguid kokku",
    kpiIssued              = "VÄLJASTATUD",
    kpiRedeemed            = "LUNASTATUD",
    kpiLiability           = "KOHUSTUSED",
    kpiVoids               = "TÜHISTATUD",
    operationsCount        = "tehingut",
    settingsTitle          = "Seaded",
    settingsTerminalInfo   = "Terminali teave",
    settingsTerminalId     = "Terminali ID",
    settingsLocation       = "Asukoht",
    settingsMerchantId     = "Kaupmehe ID",
    settingsCurrency       = "Valuuta",
    settingsNetwork        = "Võrk",
    settingsAlerts         = "Teavitused",
    settingsTelegram       = "Telegrami teavitused",
    settingsBotToken       = "Boti token",
    settingsChatId         = "Chat ID",
    settingsDisplay        = "Ekraan",
    settingsDarkMode       = "Tume režiim",
    settingsKiosk          = "Kiosk-režiim",
    settingsKioskLock      = "Ülesannete lukustus",
    settingsKioskInfo      = "Kiosk-režiim nõuab Device Owner poliitikat. Võtke ühendust IT-administraatoriga.",
    settingsDatabase       = "Andmebaas",
    settingsExportCsv      = "Ekspordi andmebaas (CSV)",
    settingsProvision      = "Uuesti registreerimine",
    settingsScanQr         = "Skanni QR-koodi",
    settingsLanguage       = "Keel",
    errNfcRead             = "NFC viga: ",
    errInsufficientBalance = "Ebapiisav saldo",
    errExpired             = "Kaart aegunud",
    errCloneDetected       = "⚠ Kaardi allkiri on vale — võimalik võltsing.",
    errWrongMerchant       = "See kaart kuulub teise kaupmehe võrku.",
    errAuthFailed          = "Autentimine ebaõnnestus",
    back                   = "Tagasi",
    confirm                = "Kinnita",
    cancel                 = "Tühista",
    currency               = "EUR",
    months                 = "k",
    cancelTitle                    = "Tehingu tühistamine",
    cancelSelectTxPrompt           = "Valige tühistatav tehing",
    cancelTapCardPrompt            = "Aseta kaart lugerile kviitungi #%s tühistamiseks",
    cancelSuccess                  = "✓ Kviitung #%s edukalt tühistatud",
    cancelNotTodayError            = "Tehing ei ole tehtud täna.",
    cancelCardMismatchError        = "Loetud kaart ei vasta tehingule.",
    cancelInsufficientBalanceError = "Kaardil pole piisavalt vahendeid.",
    cancelAlreadyVoidedError       = "Tehing on juba tühistatud.",
    cancelImpossibleComment        = "Tühistamine võimatu.",
    primaryOperationBadge          = "★ PEAMINE",
    opIssueSubtitle                = "Uue kaardi väljastamine või laadimine",
    opRedeemSubtitle               = "Ostude tasumine või saldo lunastamine",
    errExhausted                   = "Kaardi saldo on täielikult ära kasutatud.",
    overwriteBalanceTitle          = "Hoiatus! Kaardil on vahendeid",
    overwriteBalanceMessage        = "Sellel kaardil on juba aktiivne saldo: %s. Uuesti väljastamine kustutab olemasoleva saldo! Kas jätkata?",
    overwriteBalanceConfirm        = "Kirjuta saldo üle",
    exitConfirmTitle               = "Välju programmist",
    exitConfirmMessage             = "Kas olete kindel, et soovite välja logida või kasutajat vahetada?",
    exitConfirmButton              = "Kinnita väljumine",
    shiftClosedSuccess             = "Vahetus on edukalt suletud. Z-aruanne koostatud.",
    shiftAlreadyClosed             = "Tänane vahetus on juba suletud.",
    tgSentSuccess                  = "Z-aruanne edukalt Telegrammi saadetud.",
    tgSendFailed                   = "Viga Telegrammi saatmisel: %s",
    tgNotConfigured                = "Telegram ei ole terminali seadetes seadistatud.",
    settingsTgTokenPrompt          = "Bot Token (nt 123456:ABC...)",
    settingsTgChatPrompt           = "Chat ID / Kanal (nt -100... või @kanal)",
    settingsTgChannelHint          = "Kanal: @kanal või -100... (Bot PEAB olema kanali administraator postitamise õigusega)",
    settingsSave                   = "Salvesta",
)

val StringsLt = AppStrings(
    appName                = "🦊 FoxyGift POS",
    selectOperation        = "Pasirinkite operaciją",
    opIssue                = "IŠDAVIMAS / PAPILD.",
    opRedeem               = "PANAUDOTI KORTELĘ",
    opBalance              = "BALANSAS",
    opProlong              = "PRATĘSTI",
    opVoid                 = "ANULIUOTI",
    opZReport              = "Z-ATASKAITA",
    opDailyOperations      = "DIENOS OPERACIJOS",
    logout                 = "Atsijungti",
    switchUser             = "Pakeisti naudotoją",
    roleAdmin              = "Administratorius",
    roleCashier            = "Kasininkas",
    roleProlong            = "Prižiūrėtojas",
    loggedInAs             = "Rolė",
    accessDenied           = "Prieiga uždrausta",
    adminPinRequired       = "Reikalingas administratoriaus PIN",
    prolongPinRequired     = "Reikalingas pratęsimo arba admin PIN",
    enterPinToAuthorize    = "Įveskite PIN operacijos patvirtinimui",
    authorizeSuccess       = "Autorizacija sėkminga",
    invalidPin             = "Neteisingas PIN",
    dailyOperationsTitle   = "Dienos operacijų žurnalas",
    dailyTotalOperations   = "Iš viso operacijų",
    dailyTurnover          = "Apyvarta",
    receiptNo              = "Kvitas #",
    time                   = "Laikas",
    cardNumber             = "Kortelės numeris",
    amount                 = "Suma",
    balanceAfter           = "Likutis",
    status                 = "Būsena",
    noOperationsToday      = "Šioje pamainoje operacijų nerasta",
    filterAll              = "Visi",
    filterIssue            = "Išduota",
    filterRedeem           = "Panaudota",
    filterProlong          = "Pratęsta",
    filterVoid             = "Anuliuota",
    exportCsv              = "Eksportuoti CSV",
    exportSuccess          = "CSV failas persiųstas į el. paštą",
    exportError            = "Nepavyko eksportuoti CSV",
    pinUnlockPrompt        = "Įveskite PIN atrakinimui",
    wrongPinRemaining      = "Neteisingas PIN. Liko bandymų: %d",
    wrongPinNextLocks      = "Neteisingas PIN. Kita klaida užblokuos terminalą.",
    keyboardLocked         = "Klaviatūra užrakinta: %d s",
    permanentlyLocked      = "🔴 VISAM LAIKUI UŽBLOKUOTA",
    scanQrToUnlock         = "Nuskaitykite QR atrakinimui",
    provisionTerminal      = "Terminalo nustatymas",
    scanQr                 = "Nuskaityti QR",
    nfcTapCard             = "Pridėkite kortelę prie skaitytuvo",
    nfcReading             = "Skaitoma kortelė…",
    nfcWriting             = "Rašoma į kortelę… NEATIMKITE",
    nfcDoNotRemove         = "NEATIMKITE KORTELĖS",
    nfcKeepOnReader        = "Laikykite kortelę ant skaitytuvo iki patvirtinimo",
    nfcSuccess             = "✓ ",
    nfcFailed              = "✗ Operacija nepavyko",
    nfcCardBalance         = "Kortelės balansas",
    nfcClose               = "Uždaryti",
    issueTitle             = "Išduoti / Papildyti kortelę",
    issueNominalValue      = "Suma",
    issueValidity          = "Galiojimo laikas",
    issueTapButton         = "PRIDĖTI KORTELĘ  •  %s",
    redeemTitle            = "Panaudoti dovanų kortelę",
    redeemAmountLabel      = "Suma",
    redeemTapButton        = "PRIDĖTI KORTELĘ  •  %s",
    balanceTitle           = "Balanso patikrinimas",
    balanceExpiry          = "Galioja iki",
    balanceExpired         = "⚠ PASIBAIGĖ",
    prolongTitle           = "Pratęsti kortelę",
    prolongMonths          = "Pridėti mėnesių",
    prolongCurrentExpiry   = "Dabartinis terminas",
    prolongTapButton       = "PRIDĖTI KORTELĘ  •  +%d MĖN.",
    prolongCardTitle       = "Kortelės galiojimo pratęsimas",
    extendCardBy           = "Pratęsti kortelę",
    extensionPeriod        = "Pratęsimo laikotarpis",
    prolongCardInstruction = "Pridėkite kortelę prie skaitytuvo galiojimui pratęsti %d mėn.",
    zReportShiftTitle      = "Z-Ataskaita — Pamaina %s",
    closeShift             = "UŽDARYTI PAMAINĄ",
    sendToTelegram         = "Siųsti į Telegram",
    totalTransactions      = "Iš viso operacijų",
    kpiIssued              = "IŠDUOTA",
    kpiRedeemed            = "PANAUDOTA",
    kpiLiability           = "ĮSIPAREIGOJIMAI",
    kpiVoids               = "ANULIUOTA",
    operationsCount        = "operacijos",
    settingsTitle          = "Nustatymai",
    settingsTerminalInfo   = "Terminalo informacija",
    settingsTerminalId     = "Terminalo ID",
    settingsLocation       = "Vieta",
    settingsMerchantId     = "Prekybininko ID",
    settingsCurrency       = "Valiuta",
    settingsNetwork        = "Tinklas",
    settingsAlerts         = "Pranešimai",
    settingsTelegram       = "Telegram pranešimai",
    settingsBotToken       = "Boto žetonas",
    settingsChatId         = "Chat ID",
    settingsDisplay        = "Ekranas",
    settingsDarkMode       = "Tamsus režimas",
    settingsKiosk          = "Kioskо režimas",
    settingsKioskLock      = "Užduočių blokavimas",
    settingsKioskInfo      = "Kiosk režimui reikalinga Device Owner politika. Kreipkitės į IT administratorių.",
    settingsDatabase       = "Duomenų bazė",
    settingsExportCsv      = "Eksportuoti duomenų bazę (CSV)",
    settingsProvision      = "Pakartotinė registracija",
    settingsScanQr         = "Nuskaityti QR kodą",
    settingsLanguage       = "Kalba",
    errNfcRead             = "NFC klaida: ",
    errInsufficientBalance = "Nepakankamas balansas",
    errExpired             = "Kortelės galiojimas pasibaigė",
    errCloneDetected       = "⚠ Kortelės parašas neteisingas — galimas suklastojimas.",
    errWrongMerchant       = "Ši kortelė priklauso kitam prekybininko tinklui.",
    errAuthFailed          = "Autentifikacija nepavyko",
    back                   = "Atgal",
    confirm                = "Patvirtinti",
    cancel                 = "Atšaukti",
    currency               = "EUR",
    months                 = "mėn.",
    cancelTitle                    = "Sandorio anuliavimas",
    cancelSelectTxPrompt           = "Pasirinkite anuliuojamą sandorį",
    cancelTapCardPrompt            = "Pridėkite kortelę kvito #%s anuliavimui",
    cancelSuccess                  = "✓ Kvitas #%s sėkmingai anuliuotas",
    cancelNotTodayError            = "Sandoris atliktas ne šiandien.",
    cancelCardMismatchError        = "Nuskaityta kortelė nesutampa su sandoriu.",
    cancelInsufficientBalanceError = "Kortelėje nepakankamai lėšų.",
    cancelAlreadyVoidedError       = "Sandoris jau anuliuotas.",
    cancelImpossibleComment        = "Anuliavimas neįmanomas.",
    primaryOperationBadge          = "★ PAGRINDINĖ",
    opIssueSubtitle                = "Naujos kortelės išdavimas arba papildymas",
    opRedeemSubtitle               = "Pirkimo apmokėjimas arba lėšų nurašymas",
    errExhausted                   = "Kortelės likutis visiškai išnaudotas.",
    overwriteBalanceTitle          = "Dėmesio! Kortelėje yra lėšų",
    overwriteBalanceMessage        = "Šioje kortelėje jau yra aktyvus likutis: %s. Pakartotinis išdavimas ištrins esamas lėšas! Tęsti?",
    overwriteBalanceConfirm        = "Perrašyti likutį",
    exitConfirmTitle               = "Išeiti iš programos",
    exitConfirmMessage             = "Ar tikrai norite atsijungti arba pakeisti naudotoją?",
    exitConfirmButton              = "Patvirtinti išėjimą",
    shiftClosedSuccess             = "Pamaina sėkmingai uždaryta. Z-ataskaita sugeneruota.",
    shiftAlreadyClosed             = "Šiandienos pamaina jau uždaryta.",
    tgSentSuccess                  = "Z-ataskaita sėkmingai išsiųsta į Telegram.",
    tgSendFailed                   = "Klaida siunčiant į Telegram: %s",
    tgNotConfigured                = "Telegram nesukonfigūruotas terminalo nustatymuose.",
    settingsTgTokenPrompt          = "Bot Token (pvz., 123456:ABC...)",
    settingsTgChatPrompt           = "Chat ID / Kanalas (pvz., -100... arba @kanalas)",
    settingsTgChannelHint          = "Kanalas: @kanalas arba -100... (Botas PRIVALO būti kanalo administratorius su žinučių skelbimo teise)",
    settingsSave                   = "Išsaugoti",
)

/** All available languages with their display names. */
enum class AppLanguage(val code: String, val displayName: String, val flag: String) {
    EN("en", "English",   "🇬🇧"),
    RU("ru", "Русский",   "🇷🇺"),
    LV("lv", "Latviešu", "🇱🇻"),
    ET("et", "Eesti",     "🇪🇪"),
    LT("lt", "Lietuvių", "🇱🇹");

    companion object {
        fun fromCode(code: String) = entries.firstOrNull { it.code == code } ?: EN
    }
}

fun AppLanguage.strings(): AppStrings = when (this) {
    AppLanguage.EN -> StringsEn
    AppLanguage.RU -> StringsRu
    AppLanguage.LV -> StringsLv
    AppLanguage.ET -> StringsEt
    AppLanguage.LT -> StringsLt
}

/** CompositionLocal providing current AppStrings throughout the compose tree. */
val LocalStrings = compositionLocalOf<AppStrings> { StringsEn }
